[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.49.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.49.2"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.49.2"

#
# Headers
#
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'none'; script-src 'self' https://widget.sndcdn.com https://cdnjs.cloudflare.com https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data: *; font-src https://cdnjs.cloudflare.com; frame-src https://w.soundcloud.com;"

[[headers]]
  for = "/**/*.svg"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; frame-ancestors 'none'; style-src 'self' 'unsafe-inline';"

#
# Redirects
#
[[redirects]]
  from = "/show/*"
  to = "/shows/:splat"
  status = 301

[[redirects]]
  from = "/tnm-extra/*"
  to = "/extras/:splat"
  status = 301

[[redirects]]
  from = "/shows/2017-04-11-tnm-extra-oathbreaker-caro-tanghe/"
  to = "/extras/2017-04-11-tnm-extra-oathbreaker-caro-tanghe/"
  status = 301

[[redirects]]
  from = "/shows/2017-04-25-tnm-extra-festival-debate/"
  to = "/extras/2017-04-25-tnm-extra-festival-debate/"
  status = 301

[[redirects]]
  from = "/shows/2017-07-21-21-rip-chester-bennington/"
  to = "/shows/2017-07-21-rip-chester-bennington/"
  status = 301

[[redirects]]
  from = "/shows/page-2/"
  to = "/shows/page/2/"
  status = 301
